deubugging dockerfile2

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -4,99 +4,137 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Record start time and names
-      run: |
-        echo "$(date -Iminutes)" > log.txt
-        echo "Maya Ben Zeev, Noga Brenner, Eden Zehavy" >> log.txt
+      - name: Record start time
+        run: echo "$(date -Iminutes)" > log.txt
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
+      - name: Record submitter names
+        run: echo "Maya Ben Zeev, Noga Brenner, Eden Zehavy" >> log.txt
 
-    - name: Build Docker image
-      run: |
-        if docker build -t books-service:latest -f ./book-service/Dockerfile ./book-service; then
-          echo "image successfully built" >> log.txt
-          docker save books-service:latest -o /tmp/image.tar
-        else
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+        with:
+          context: ./book-service
+          outputs: type=docker, dest=/tmp/image.tar
+
+      - name: Status on Build with Docker image
+        if: success()
+        run: echo "image successfully built" >> log.txt
+
+      - name: Status on Build with Docker image
+        if: failure()
+        run: |
           echo "image not able to be built" >> log.txt
           exit 1
 
-    - name: Upload image and logs
-      uses: actions/upload-artifact@v4
-      with:
-        name: build-artifacts
-        path: |
-          /tmp/image.tar
-          log.txt
+      - name: Upload image artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: book-service
+          path: /tmp/image.tar
+
+      - name: Upload logs
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: logs
+          path: log.txt
 
   test:
     needs: build
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Download Build Artifacts
-      uses: actions/download-artifact@v4
-      with:
-        name: build-artifacts
-        path: /tmp
+      - name: Download Docker Image Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: book-service
+          path: /tmp
 
-    - name: Load Docker image
-      run: |
-        docker load --input /tmp/image.tar
-        docker run -d --name books-service -p 5001:80 books-service:latest
-        echo "Container up and running" >> /tmp/log.txt
+      - name: Load Docker image from previous workflows
+        run: docker load --input /tmp/image.tar
 
-    - name: Check container and Execute pytest
-      run: |
-        docker ps
-        if docker exec books-service ls -laR /app; then
-          if docker exec books-service python -m pytest -v /app/tests/; then
-            echo "tests succeeded" >> /tmp/log.txt
+      - name: Check books image is loaded
+        run: docker image ls
+
+      - name: Start Docker Compose
+        run: |
+          if docker-compose up -d; then
+            echo "Container up and running" >> log.txt
           else
-            echo "tests failed" >> /tmp/log.txt
+            echo "Container failed to run" >> log.txt
             exit 1
           fi
-        else
-          echo "Directory /app/tests not found" >> /tmp/log.txt
-          exit 1
 
-    - name: Upload test results and logs
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-results-and-logs
-        path: /tmp/log.txt
+      - name: Check container is running
+        run: |
+          docker ps
+          docker exec books-service ls -laR /app
+
+      - name: Execute pytest inside the container
+        run: |
+          if docker exec books-service python -m pytest -v /app/tests/assn3_tests.py > assn3_test_results.txt; then
+            echo "tests succeeded" >> log.txt
+          else
+            echo "tests failed" >> log.txt
+            exit 1
+          fi
+
+      - name: Upload test results and logs
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results-and-logs
+          path: |
+            log.txt
+            assn3_test_results.txt
 
   query:
     needs: test
     runs-on: ubuntu-latest
-    env:
-      BOOKS_URL: 'http://127.0.0.1:5001/books'
     steps:
-    - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v3
 
-    - name: Start Docker Compose
-      run: |
-        docker-compose up -d
+      - name: Start Docker Compose
+        run: docker-compose up -d
 
-    - name: Initialize Data and Issue Queries
-      run: |
-        for isbn in "9780520343641" "9780385050784" "9780394558783" "9780195810400" "9780553294385" "9780553293364"; do
-          curl -X POST -H "Content-Type: application/json" -d "{\"title\": \"$(jq -r '.title' book-data/$isbn.json)\", \"ISBN\": \"$isbn\", \"genre\": \"$(jq -r '.genre' book-data/$isbn.json)\"}" ${{ env.BOOKS_URL }}
-        done
+      - name: Check container is running
+        run: docker ps
 
-        touch response.txt
-        while read -r line; do
-          echo "query: $line" >> response.txt
-          response=$(curl -s -w "\n%{http_code}" "${{ env.BOOKS_URL }}$line")
-          echo "response: ${response%$'\n'*}" >> response.txt
-        done < query.txt
+      - name: Post Books to Initialize Data
+        run: |
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "Adventures of Huckleberry Finn", "ISBN": "9780520343641", "genre": "Fiction"}' ${{ env.BOOKS_URL }}
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "The Best of Isaac Asimov", "ISBN": "9780385050784", "genre": "Science Fiction"}' ${{ env.BOOKS_URL }}
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "Fear No Evil", "ISBN": "9780394558783", "genre": "Biography"}' ${{ env.BOOKS_URL }}
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}' ${{ env.BOOKS_URL }}
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}' ${{ env.BOOKS_URL }}
+          curl -X POST -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}' ${{ env.BOOKS_URL }}      
+      
 
-    - name: Upload Query Results
-      uses: actions/upload-artifact@v3
-      with:
-        name: query_results
-        path: response.txt
+      - name: Issue Queries and Record Results
+        run: |
+          touch response.txt
+          while read -r line; do
+            echo "query: $line" >> response.txt
+            response_body=$(curl -s -w "\n%{http_code}" "${{ env.BOOKS_URL }}$line")
+            status_code=$(echo "$response_body" | tail -n1)
+            response_body=$(echo "$response_body" | head -n -1)
+            
+            if [[ "$status_code" -eq 200 ]]; then
+              echo "response: $response_body" >> response.txt
+            else
+              echo "response: error $status_code" >> response.txt
+            fi
+          done < query.txt
+
+      - name: Upload Results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: query_results
+          path: response.txt
