new day new try

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -11,36 +11,43 @@ jobs:
         run: echo "$(date -Iminutes)" > log.txt
 
       - name: Record submitter names
-        run: echo "Maya Ben Zeev, Noga Brenner, Eden Zehavy" >> log.txt
+        run: echo "Maya Ben Zeev, Noga Brenner, Eden Zehavy" >> /tmp/log.txt
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-        with:
-          context: ./book-service
-          outputs: type=docker, dest=/tmp/image.tar
 
-      - name: Status on Build with Docker image
-        if: success()
-        run: echo "image successfully built" >> log.txt
-
-      - name: Status on Build with Docker image
-        if: failure()
+      - name: Build and export image to tarfile #TODO: check if need to do /tmp/log.txt
         run: |
-          echo "image not able to be built" >> log.txt
-          exit 1
+          if docker-compose build; then
+            echo "image successfully built" >> /tmp/log.txt
+            else
+            echo "image not able to be built" >> /tmp/log.txt
+            exit 1 
+          fi
 
-      - name: Upload image artifact
-        uses: actions/upload-artifact@v4
+      - name: Export images to a tar file
+        run: |
+          docker save book-service:latest > /tmp/book-service.tar
+          docker save mongo:latest > /tmp/mongo.tar
+
+      - name: Upload books image artifact
+        uses: actions/upload-artifact@v3
         with:
-          name: book-service
-          path: /tmp/image.tar
+          name: book-service-image
+          path: /tmp/book-service.tar
+
+      - name: Upload MongoDB image artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: mongo-image
+          path: /tmp/mongo.tar
 
       - name: Upload logs
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: logs
-          path: log.txt
+          path: /tmp/log.txt
 
   test:
     needs: build
@@ -50,37 +57,50 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Download Docker Image Artifact
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v3
         with:
-          name: book-service
           path: /tmp
 
-      - name: Load Docker image from previous workflows
-        run: docker load --input /tmp/image.tar
+      - name: Load Docker images from previous workflows
+        run: |
+          docker load --input /tmp/book-service.tar
+          docker load --input /tmp/mongo.tar
 
-      - name: Check books image is loaded
+      - name: Check images are loaded
         run: docker image ls
 
       - name: Start Docker Compose
         run: |
           if docker-compose up -d; then
-            echo "Container up and running" >> log.txt
+            echo "Container up and running" >> /tmp/log.txt
           else
-            echo "Container failed to run" >> log.txt
+            echo "Container failed to run" >> /tmp/log.txt
             exit 1
           fi
 
-      - name: Check container is running
+      - name: Check container is running #TODO: for us "docker exec books-service ls -laR /app  "
         run: |
           docker ps
-          docker exec books-service ls -laR /app
+          docker exec books-service ls -laR /app  
 
-      - name: Execute pytest inside the container
+      # Set up python env for running tests
+      - name: Set up Python
+        uses: actions/setup-python@v4
+
+      - name: Install dependencies
         run: |
-          if docker exec books-service python -m pytest -v /app/tests/assn3_tests.py > assn3_test_results.txt; then
-            echo "tests succeeded" >> log.txt
+          python -m pip install --upgrade pip
+          pip install pytest 
+          pip install requests
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
+      - name: Test with pytest
+        run: |
+          cd tests
+          if pytest -v assn3_tests.py > assn3_test_results.txt; then
+            echo "tests succeeded" >> /tmp/log.txt
           else
-            echo "tests failed" >> log.txt
+            echo "tests failed" >> /tmp/log.txt
             exit 1
           fi
 
@@ -90,8 +110,12 @@ jobs:
         with:
           name: test-results-and-logs
           path: |
-            log.txt
-            assn3_test_results.txt
+            /tmp/log.txt
+            tests/assn3_test_results.txt
+
+      - name: Shut down docker compose
+        run: docker-compose down
+            
 
   query:
     needs: test
@@ -114,7 +138,6 @@ jobs:
           curl -X POST -H "Content-Type: application/json" -d '{"title": "The Adventures of Tom Sawyer", "ISBN": "9780195810400", "genre": "Fiction"}' ${{ env.BOOKS_URL }}
           curl -X POST -H "Content-Type: application/json" -d '{"title": "I, Robot", "ISBN": "9780553294385", "genre": "Science Fiction"}' ${{ env.BOOKS_URL }}
           curl -X POST -H "Content-Type: application/json" -d '{"title": "Second Foundation", "ISBN": "9780553293364", "genre": "Science Fiction"}' ${{ env.BOOKS_URL }}      
-      
 
       - name: Issue Queries and Record Results
         run: |
