update

diff --git a/.github/workflows/assignment3.yml b/.github/workflows/assignment3.yml
--- a/.github/workflows/assignment3.yml
+++ b/.github/workflows/assignment3.yml
@@ -8,15 +8,15 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Record start time
-        run: echo "$(date -Iminutes)" > log.txt
+        run: echo "$(date -Iminutes)" > /tmp/log.txt
 
-      - name: Record submitter names
+      - name: Record submitters names
         run: echo "Maya Ben Zeev, Noga Brenner, Eden Zehavy" >> /tmp/log.txt
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Build and export image to tarfile #TODO: check if need to do /tmp/log.txt
+      - name: Build image to tarfile #TODO: check if need to do /tmp/log.txt
         run: |
           if docker-compose build; then
             echo "image successfully built" >> /tmp/log.txt
@@ -24,9 +24,6 @@ jobs:
             echo "image not able to be built" >> /tmp/log.txt
             exit 1 
           fi
-
-      - name: List Docker images after build
-        run: docker images
 
       - name: Export images to a tar file
         run: |
@@ -63,6 +60,12 @@ jobs:
         run: |
           docker load --input /tmp/books-service.tar
 
+      - name: Download log file
+        uses: actions/download-artifact@v4
+        with:
+          name: logs
+          path: /tmp
+
       - name: Check images are loaded
         run: docker image ls
 
@@ -86,8 +89,8 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pytest 
-          pip install requests
+          pip install requests 
+          pip install pytest
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       - name: Test with pytest
@@ -104,12 +107,13 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: test-results-and-logs
+          name: logs
           path: |
             /tmp/log.txt
             tests/assn3_test_results.txt
 
       - name: Shut down docker compose
+        if: always()
         run: docker-compose down
             
 
@@ -133,10 +137,16 @@ jobs:
           docker load --input /tmp/books-service.tar
 
       - name: Start Docker Compose
-        run: docker-compose up -d
+        run: |
+          if docker-compose up -d; then
+            echo "Container up and running" >> /tmp/log.txt
+          else
+            echo "Container failed to run" >> /tmp/log.txt
+            exit 1
+          fi
 
-      - name: Wait for the server to start
-        run: sleep 10
+      # - name: Wait for the server to start
+      #   run: sleep 5
 
       - name: Check container is running
         run: docker ps
@@ -183,3 +193,7 @@ jobs:
         with:
           name: query_results
           path: response.txt
+
+      - name: Shut down Docker Compose
+        if: always()
+        run: docker-compose down
